parse_config:
  raw_binding_map:
    "&caps_word": Caps Word
    "&sk LSHFT": One Shot Shift
    "&kp LSHFT": Shift
    "&kp GLOBE": Globe
    "&sentence_end_v1_TKZ": Sentence End
    "&kp LG(LS(N3))": Screenshot
    "&kp LG(LS(N4))": Area Screenshot
    "&kp LC(LG(LS(N4)))": Copy Area Screenshot
    "&kp LC(LG(LS(N3)))": Copy Screenshot
    "&kp LS(N1)": "!"
    "&kp LS(N2)": "@"
    "&kp LS(N3)": "#"
    "&kp LS(N4)": "$"
    "&kp LS(N5)": "%"
    "&kp LS(N6)": "^"
    "&kp LS(N7)": "&"
    "&kp LS(N8)": "*"
    "&kp LS(N9)": "("
    "&kp LS(N0)": ")"
    "&kp LS(MINUS)": "_"
    "&kp LS(EQUAL)": "+"
    "&kp LS(LBKT)": "{"
    "&kp LS(RBKT)": "}"
    "&kp LS(BSLH)": "|"
    "&kp LS(FSLH)": "?"
    "&kp LS(SEMI)": ":"
    "&kp LS(SINGLE_QUOTE)": '"'
    "&kp LS(GRAVE)": "~"
    "&kp LS(COMMA)": "<"
    "&kp LS(DOT)": ">"
    "&arrow_morph": Arrow
    "&arrow_plain_macro": "->"
    "&arrow_shift_macro": "=>"
    "&arrow_alt_macro": "<->"
    "&arrow_shift_alt_macro": "<=>"
    "&symb_dotdot_v1_TKZ": ".."
    "&cur_SELECT_LINE_macos_v1_TKZ": Select Line
    "&cur_SELECT_WORD_macos_v1_TKZ": Select Word
    "&cur_SELECT_WORD_BACK_macos_v1_TKZ": Select Word Back
    "&nav_SEARCH_SELECTED_macos_v1_TKZ": Search Selected
    "&cyclotab_v1_TKZ": Cyclotab
    "&tog_lock_v1_TKZ LAYER_Cursor": Cursor Lock
    "&tog LAYER_Mouse": Mouse Toggle
    "&kp LC(LS(TAB))": Prev Tab
    "&kp LC(TAB)": Next Tab
    "&kp LS(TAB)": Shift Tab
    "&kp LG(LBKT)": Browser Back
    "&kp LG(RBKT)": Browser Forward
    "&kp LG(LS(Z))": Redo
    "&kp LS(LG(Z))": Redo
    "&kp LG(LS(G))": Find Prev
    "&kp LS(LG(G))": Find Prev
    "&kp LG(G)": Find Next
    "&kp LG(C)": Copy
    "&kp LG(R)": Cmd+R
    "&kp LG(F)": Find
    "&kp LG(L)": Cmd+L
    "&kp LG(V)": Paste
    "&kp LG(X)": Cut
    "&kp LG(Z)": Undo
    "&kp LG(F3)": Cmd+F3
    "&kp LS(LG(V))": Cmd+Shift+V
    "&kp LG(LS(V))": Cmd+Shift+V
    "&mmv MOVE_LEFT": Mouse Left
    "&mmv MOVE_RIGHT": Mouse Right
    "&mmv MOVE_UP": Mouse Up
    "&mmv MOVE_DOWN": Mouse Down
    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MB4": Back Button
    "&mkp MB5": Forward Button
    "&mouse_gesture": Gesture
    "&mstr1_v1_TKZ": Hola Macro
    "&bootloader": Bootloader
    "&sys_reset": Reset
    "&bt_0": BT 0
    "&bt_1": BT 1
    "&bt_2": BT 2
    "&bt_3": BT 3
    "&out OUT_USB": USB Out
