name: Draw keymap

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "keymap_drawer.config.yaml"
      - ".github/workflows/draw-keymap.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      west_config_path: ""
      output_folder: "keymap-drawer"
      parse_args: "go60:'-c 12'"
